replicaCount: 2
image:
  # Update with your ECR URL after running: terraform output ecr_frontend_url
  repository: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/devopsflow/frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  host: devops-flow.yourdomain.com
