replicaCount: 2
image:
  repository: your-docker-repo/devops-flow-frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  host: devops-flow.yourdomain.com
